name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo GitHub Actions!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-node@v4.0.1
      - name: Setup Node.js environment
        run: echo "Hola mundo"
      - name: Correr script
        run: node index.js
